{
 "title": "Sequin",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Ingested by Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(replication_slot_id, slot_name) (rate(sequin_messages_ingested_count[$__rate_interval]))",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Messages Delivered by Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(consumer_id, consumer_name) (rate(sequin_message_deliver_success_count[$__rate_interval]))",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Delivery Success % by Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(consumer_id, consumer_name) ((rate(sequin_message_deliver_success_count[10m])) / (rate(sequin_message_deliver_attempt_count[10m])))",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Delivery Success % by Sink",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(consumer_id, consumer_name) (increase(sequin_message_deliver_success_count[5m])) \n/ \nsum by(consumer_id, consumer_name) (increase(sequin_message_deliver_attempt_count[5m]))",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Slot Ingestion Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "sequin_ingestion_latency_us", "legendFormat": "{{slot_name}}" }
   ]
  },
  {
   "title": "Sink Internal Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, success, consumer_id, consumer_name) (rate(sequin_internal_latency_us_bucket[$__rate_interval])))",
     "legendFormat": "{{consumer_name}}: {{success}}"
    }
   ]
  },
  {
   "title": "Sink Deliver Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, success, consumer_id, consumer_name) (rate(sequin_delivery_latency_us_bucket[$__rate_interval])))",
     "legendFormat": "{{consumer_name}}: {{success}}"
    }
   ]
  },
  {
   "title": "SlotProcessorServer operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(sequin_slot_processor_server_operation_percent) by (replication_id, slot_name, operation)",
     "legendFormat": "{{slot_name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "SlotMessageHandler operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(sequin_slot_message_handler_operation_percent) by (replication_id, slot_name, operation)",
     "legendFormat": "{{slot_name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "SlotMessageStore operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(sequin_slot_message_store_operation_percent) by (consumer_id, consumer_name, operation)",
     "legendFormat": "{{consumer_name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Beam Reductions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(erlang_vm_statistics_reductions_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beam Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "erlang_vm_memory_bytes_total", "legendFormat": "{{kind}} memory" }
   ]
  }
 ]
}