#!/bin/bash
set -e

echo "=== Terraform Backend Configuration Setup ==="
echo ""

# Check if backend files already exist
if [[ -f "terraform/infra/backend.tfbackend" ]] || [[ -f "terraform/app/backend.tfbackend" ]]; then
    echo "⚠️  backend.tfbackend files already exist!"
    read -p "Do you want to overwrite them? (y/N): " overwrite
    if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
        echo "Aborted."
        exit 1
    fi
fi

echo "Setting up S3 backend configuration for both infra and app..."
echo ""

# Collect user input
read -p "Enter your S3 bucket name for Terraform state: " bucket
read -p "Enter your AWS region (default: us-west-2): " region
region=${region:-us-west-2}

# Create infra backend config
echo "Creating infra backend config..."
cat > terraform/infra/backend.tfbackend << EOF
# S3 Backend Configuration - Infrastructure
# Generated by './init-terraform.sh'

bucket = "$bucket"
key    = "infra/terraform.tfstate"
region = "$region"
encrypt = true

EOF

# Create app backend config
echo "Creating app backend config..."
cat > terraform/app/backend.tfbackend << EOF
# S3 Backend Configuration - Application  
# Generated by './init-terraform.sh'

bucket = "$bucket"
key    = "app/terraform.tfstate"
region = "$region"
encrypt = true

EOF

# Create app remote state config
echo "Creating app remote state config..."
cat > terraform/app/remote-state.auto.tfvars << EOF
# Auto-generated remote state configuration for app/
# Generated by './init-terraform.sh' from infra/backend.tfbackend

infra_state_bucket = "$bucket"
infra_state_region = "$region"

EOF

echo ""
echo "✅ Backend configurations created:"
echo "   - terraform/infra/backend.tfbackend (key: infra/terraform.tfstate)"
echo "   - terraform/app/backend.tfbackend (key: app/terraform.tfstate)"
echo "   - terraform/app/remote-state.auto.tfvars (infra state reference)"
echo ""
echo "Next steps:"
echo "For infrastructure:"
echo "1. cd terraform/infra"
echo "2. terraform init -backend-config=backend.tfbackend"
echo ""
echo "For application:"
echo "1. cd terraform/app"  
echo "2. terraform init -backend-config=backend.tfbackend"
echo ""

# Offer to create S3 bucket
read -p "Do you want me to create the S3 bucket if it doesn't exist? (Y/n): " create_bucket
create_bucket=${create_bucket:-Y}

if [[ "$create_bucket" = "Y" || "$create_bucket" = "y" || "$create_bucket" = "" ]]; then
    echo ""
    echo "🪣 Creating S3 bucket if it doesn't exist..."
    
    if aws s3 ls "s3://$bucket" >/dev/null 2>&1; then
        echo "✅ Bucket $bucket already exists"
    else
        echo "Creating bucket: $bucket in region: $region"
        if aws s3 mb "s3://$bucket" --region "$region"; then
            echo "✅ Bucket $bucket created successfully"
        else
            echo "❌ Failed to create bucket. Please create it manually or check your AWS credentials"
        fi
    fi
fi

echo ""
echo "Note: Make sure you have proper AWS credentials configured!"